[window]
dynamic_title = false
padding = { x = 10, y = 10 }

[font]
size = 13
normal = { family = "Hack Nerd Font", style = "Regular" }
bold = { family = "Hack Nerd Font", style = "Bold" }
italic = { family = "Hack Nerd Font", style = "Italic" }
offset = { x = 1, y = 4 }

[cursor]
unfocused_hollow = false

[mouse]
bindings = [
    { mouse = "Right", action = "Copy" },
]

[keyboard]
bindings = [
    { key = "Up", mods = "Control", action = "ScrollLineUp", mode = "~AppCursor | ~AppKeypad" },
    { key = "Down", mods = "Control", action = "ScrollLineDown", mode = "~AppCursor | ~AppKeypad" },
    { key = "Up", mods = "Shift", action = "ScrollPageUp", mode = "~AppCursor | ~AppKeypad" },
    { key = "Down", mods = "Shift", action = "ScrollPageDown", mode = "~AppCursor | ~AppKeypad" },
    { key = "Home", mods = "Control", action = "ScrollToTop", mode = "~AppCursor | ~AppKeypad" },
    { key = "End", mods = "Control", action = "ScrollToBottom", mode = "~AppCursor | ~AppKeypad" },
    { key = "Back", mods = "Control", chars = "\u0017" },
    { key = "f", mods = "Control", action = "SearchForward" },
    { key = "v", mods = "Control", action = "Paste" },
]

[colors.primary]
background = "#010409"
foreground = "#f0f3f6"

[colors.normal]
black   = "#0a0c10"
red     = "#ff9492"
green   = "#26cd4d"
yellow  = "#f0b72f"
blue    = "#71b7ff"
magenta = "#cb9eff"
cyan    = "#76e3ea"
white   = "#d9dee3"

[colors.bright]
black   = "#272b33"
red     = "#ffb1af"
green   = "#4ae168"
yellow  = "#f7c843"
blue    = "#91cbff"
magenta = "#dbb7ff"
cyan    = "#b3f0ff"
white   = "#d9dee3"
